AWSTemplateFormatVersion: '2010-09-09'
Description: |
  OptimNow Tag Compliance - Client Account Read-Only Access

  This template creates a read-only IAM role in your AWS account that allows
  OptimNow's MCP Tag Compliance server to scan your resources for tagging
  compliance. No compute resources are deployed in your account.

  What this template creates:
  - 1 IAM Role (read-only, ~20 permissions)
  - 0 compute resources (no EC2, no Lambda, no containers)
  - 0 data storage (no S3 buckets, no databases)

  What OptimNow can do with this role:
  - Read resource tags (EC2, RDS, S3, Lambda, ECS)
  - Read cost data (Cost Explorer)
  - Discover enabled regions
  - Nothing else. No write, no delete, no modify.

  You can revoke access at any time by deleting this CloudFormation stack.

  Source code: https://github.com/optimnow/finops-tag-compliance-mcp
  Security review: All permissions are listed in the IAM policy below.

Parameters:
  OptimNowAccountId:
    Type: String
    Description: OptimNow AWS Account ID (provided during onboarding)
    AllowedPattern: '^[0-9]{12}$'
    ConstraintDescription: Must be a 12-digit AWS account ID

  ExternalId:
    Type: String
    Description: Unique External ID for your account (provided during onboarding)
    MinLength: 16
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z0-9_-]+$'
    ConstraintDescription: Must be 16-64 alphanumeric characters

  RoleName:
    Type: String
    Default: OptimNow-TagCompliance-ReadOnly
    Description: Name for the IAM role (customize if needed)
    AllowedPattern: '^[a-zA-Z0-9_+=,.@-]+$'
    ConstraintDescription: Must be a valid IAM role name

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: OptimNow Connection Settings
        Parameters:
          - OptimNowAccountId
          - ExternalId
      - Label:
          default: Advanced Settings (optional)
        Parameters:
          - RoleName
    ParameterLabels:
      OptimNowAccountId:
        default: "OptimNow Account ID"
      ExternalId:
        default: "Your Unique External ID"
      RoleName:
        default: "IAM Role Name"

Resources:
  # ==========================================================================
  # IAM Role - Read-Only Access for Tag Compliance Scanning
  # ==========================================================================
  #
  # This role grants OptimNow read-only access to:
  # - Resource tags (via Resource Groups Tagging API and service-specific APIs)
  # - Cost data (via Cost Explorer)
  # - Region discovery (via EC2 DescribeRegions)
  #
  # This role does NOT grant:
  # - Any write, modify, or delete permissions
  # - Access to resource content (no S3 object reads, no database queries)
  # - Access to credentials, secrets, or IAM configuration
  # - Access to CloudTrail, Config, or other audit services
  #
  # The trust policy uses an External ID condition to prevent confused deputy
  # attacks (AWS security best practice).
  # ==========================================================================

  OptimNowReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: Read-only access for OptimNow Tag Compliance scanning. Revoke by deleting this CloudFormation stack.
      MaxSessionDuration: 3600  # 1 hour max session

      # Trust policy: only OptimNow account can assume, only with correct External ID
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${OptimNowAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId

      Tags:
        - Key: Application
          Value: OptimNow-TagCompliance
        - Key: Purpose
          Value: Read-only tag compliance scanning
        - Key: ManagedBy
          Value: CloudFormation
        - Key: ExternalId
          Value: !Ref ExternalId

  # ==========================================================================
  # IAM Policy - Tag & Resource Discovery (read-only)
  # ==========================================================================

  TagDiscoveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: OptimNow-TagDiscovery-ReadOnly
      Roles:
        - !Ref OptimNowReadOnlyRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # ----------------------------------------------------------------
          # Resource Groups Tagging API - Universal tag discovery
          # ----------------------------------------------------------------
          - Sid: TaggingAPIReadOnly
            Effect: Allow
            Action:
              - tag:GetResources
              - tag:GetTagKeys
              - tag:GetTagValues
            Resource: '*'

          # ----------------------------------------------------------------
          # EC2 - Instance and volume tag reading + region discovery
          # ----------------------------------------------------------------
          - Sid: EC2ReadOnly
            Effect: Allow
            Action:
              - ec2:DescribeInstances
              - ec2:DescribeTags
              - ec2:DescribeVolumes
              - ec2:DescribeRegions
            Resource: '*'

          # ----------------------------------------------------------------
          # RDS - Database instance tag reading
          # ----------------------------------------------------------------
          - Sid: RDSReadOnly
            Effect: Allow
            Action:
              - rds:DescribeDBInstances
              - rds:ListTagsForResource
            Resource: '*'

          # ----------------------------------------------------------------
          # S3 - Bucket listing and tag reading (no object access)
          # ----------------------------------------------------------------
          - Sid: S3ReadOnly
            Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketTagging
              - s3:GetBucketLocation
            Resource: '*'

          # ----------------------------------------------------------------
          # Lambda - Function listing and tag reading
          # ----------------------------------------------------------------
          - Sid: LambdaReadOnly
            Effect: Allow
            Action:
              - lambda:ListFunctions
              - lambda:ListTags
            Resource: '*'

          # ----------------------------------------------------------------
          # ECS - Service listing and tag reading
          # ----------------------------------------------------------------
          - Sid: ECSReadOnly
            Effect: Allow
            Action:
              - ecs:ListClusters
              - ecs:ListServices
              - ecs:DescribeServices
              - ecs:ListTagsForResource
            Resource: '*'

          # ----------------------------------------------------------------
          # Cost Explorer - Cost data for attribution gap analysis
          # Always operates from us-east-1 regardless of resource region
          # ----------------------------------------------------------------
          - Sid: CostExplorerReadOnly
            Effect: Allow
            Action:
              - ce:GetCostAndUsage
              - ce:GetCostAndUsageWithResources
            Resource: '*'

          # ----------------------------------------------------------------
          # STS - Identify the account (used for health checks)
          # ----------------------------------------------------------------
          - Sid: STSIdentity
            Effect: Allow
            Action:
              - sts:GetCallerIdentity
            Resource: '*'

Outputs:
  RoleArn:
    Description: |
      IAM Role ARN - provide this to OptimNow to complete the connection.
      This is the only piece of information you need to share.
    Value: !GetAtt OptimNowReadOnlyRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  ExternalIdUsed:
    Description: External ID configured for this connection (for your records)
    Value: !Ref ExternalId

  PermissionsSummary:
    Description: Summary of permissions granted
    Value: "READ-ONLY: tag:Get*, ec2:Describe*, rds:Describe*, s3:List/GetBucketTagging, lambda:List*, ecs:List/Describe*, ce:GetCost*, sts:GetCallerIdentity. ZERO write/modify/delete permissions."

  RevocationInstructions:
    Description: How to revoke OptimNow access
    Value: "Delete this CloudFormation stack to immediately revoke all access. No data is stored in your account."
