AWSTemplateFormatVersion: '2010-09-09'
Description: 'Tagging MCP Server - AWS Tag Compliance Infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name for resource tagging

  PolicyBucketName:
    Type: String
    Default: finops-mcp-config
    Description: S3 bucket name for policy configuration files

  InstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type (t3.medium recommended for 4GB RAM)

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of existing EC2 KeyPair for SSH access

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to deploy into

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet to deploy EC2 instance into

  AllowedCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR block allowed to access MCP server (restrict in production)

Resources:
  # S3 Bucket for Policy Configuration
  PolicyConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref PolicyBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Application
          Value: mcp-tagging
        - Key: Environment
          Value: !Ref EnvironmentName

  # IAM Role for EC2 Instance
  MCPServerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'mcp-tagging-role-${EnvironmentName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Application
          Value: mcp-tagging
        - Key: Environment
          Value: !Ref EnvironmentName

  # IAM Policy for Tag Compliance Operations
  MCPServerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'mcp-tagging-policy-${EnvironmentName}'
      Roles:
        - !Ref MCPServerRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # EC2 Read Access
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
              - ec2:DescribeTags
              - ec2:DescribeVolumes
              - ec2:DescribeRegions
            Resource: '*'
          # RDS Read Access
          - Effect: Allow
            Action:
              - rds:DescribeDBInstances
              - rds:DescribeDBClusters
              - rds:ListTagsForResource
            Resource: '*'
          # S3 Read Access
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketTagging
              - s3:GetBucketLocation
            Resource: '*'
          # Lambda Read Access
          - Effect: Allow
            Action:
              - lambda:ListFunctions
              - lambda:ListTags
            Resource: '*'
          # ECS Read Access
          - Effect: Allow
            Action:
              - ecs:ListClusters
              - ecs:ListServices
              - ecs:DescribeServices
              - ecs:ListTagsForResource
            Resource: '*'
          # OpenSearch Read Access
          - Effect: Allow
            Action:
              - es:ListDomainNames
              - es:DescribeDomain
              - es:DescribeDomains
              - es:ListTags
            Resource: '*'
          # Cost Explorer Access
          - Effect: Allow
            Action:
              - ce:GetCostAndUsage
              - ce:GetCostForecast
              - ce:GetTags
            Resource: '*'
          # Resource Groups Tagging API (for expanded resource coverage)
          - Effect: Allow
            Action:
              - tag:GetResources
              - tag:GetTagKeys
              - tag:GetTagValues
            Resource: '*'
          # STS for account ID lookup
          - Effect: Allow
            Action:
              - sts:GetCallerIdentity
            Resource: '*'
          # S3 access for policy config bucket
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${PolicyBucketName}/*'

  # Instance Profile
  MCPServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'mcp-tagging-profile-${EnvironmentName}'
      Roles:
        - !Ref MCPServerRole

  # Security Group
  MCPServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'mcp-tagging-sg-${EnvironmentName}'
      GroupDescription: Security group for MCP Tagging Server
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # MCP Protocol
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: !Ref AllowedCIDR
          Description: MCP Server API
        # SSH Access (restrict in production)
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCIDR
          Description: SSH Access
      SecurityGroupEgress:
        # HTTPS for AWS APIs
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: AWS API Access
        # HTTP for package downloads
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP for updates
      Tags:
        - Key: Application
          Value: mcp-tagging
        - Key: Environment
          Value: !Ref EnvironmentName

  # EC2 Instance
  MCPServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref MCPServerInstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref MCPServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          yum update -y
          
          # Install Docker
          yum install -y docker
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ec2-user
          
          # Install Docker Compose
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
          # Install Git
          yum install -y git
          
          # Create app directory
          mkdir -p /opt/tagging-mcp
          chown ec2-user:ec2-user /opt/tagging-mcp
          
          # Create policies folder for external policy mounting
          mkdir -p /home/ec2-user/mcp-policies
          chown ec2-user:ec2-user /home/ec2-user/mcp-policies
          
          # Create a default tagging policy (will be overwritten when app is deployed)
          cat > /home/ec2-user/mcp-policies/tagging_policy.json << 'POLICY'
          {
            "version": "1.0",
            "policy_name": "Default Tagging Policy",
            "description": "Default policy - update via deploy_policy.ps1",
            "required_tags": [
              {
                "name": "Environment",
                "description": "Deployment environment",
                "required": true,
                "allowed_values": ["dev", "staging", "prod"]
              },
              {
                "name": "Owner",
                "description": "Team or person responsible",
                "required": true
              },
              {
                "name": "CostCenter",
                "description": "Cost allocation code",
                "required": true
              }
            ],
            "resource_types": ["ec2:instance", "rds:db", "s3:bucket", "lambda:function"]
          }
          POLICY
          chown ec2-user:ec2-user /home/ec2-user/mcp-policies/tagging_policy.json
          
          # Signal completion
          echo "Setup complete" > /opt/tagging-mcp/setup-complete.txt
      Tags:
        - Key: Name
          Value: !Sub 'mcp-tagging-server-${EnvironmentName}'
        - Key: Application
          Value: mcp-tagging
        - Key: Environment
          Value: !Ref EnvironmentName

  # CloudWatch Log Group
  MCPServerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/mcp-tagging/${EnvironmentName}'
      RetentionInDays: 30
      Tags:
        - Key: Application
          Value: mcp-tagging
        - Key: Environment
          Value: !Ref EnvironmentName

  # Elastic IP for stable public address
  MCPServerElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub 'mcp-tagging-eip-${EnvironmentName}'
        - Key: Application
          Value: mcp-tagging
        - Key: Environment
          Value: !Ref EnvironmentName

  # Associate Elastic IP with EC2 Instance
  MCPServerEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MCPServerElasticIP.AllocationId
      InstanceId: !Ref MCPServerInstance

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MCPServerInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  ElasticIP:
    Description: Elastic IP address (stable, persists across stop/start)
    Value: !Ref MCPServerElasticIP
    Export:
      Name: !Sub '${AWS::StackName}-ElasticIP'

  MCPServerEndpoint:
    Description: MCP Server endpoint URL
    Value: !Sub 'http://${MCPServerElasticIP}:8080'
    Export:
      Name: !Sub '${AWS::StackName}-Endpoint'

  PolicyBucket:
    Description: S3 bucket for policy configuration
    Value: !Ref PolicyConfigBucket
    Export:
      Name: !Sub '${AWS::StackName}-PolicyBucket'

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref MCPServerSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  IAMRoleArn:
    Description: IAM Role ARN for the MCP Server
    Value: !GetAtt MCPServerRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  LogGroupName:
    Description: CloudWatch Log Group name
    Value: !Ref MCPServerLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'
